In [18]:
import numpy as np
from scipy.spatial.transform import Rotation as R

In [19]:
rot = R.random()
R_true = rot.as_matrix()
t_true = np.random.randn(3)
t_true = t_true / np.linalg.norm(t_true)
print("真实旋转矩阵 R_true：\n", R_true)
print("真实平移向量 t_true：", t_true)

真实旋转矩阵 R_true：
 [[-0.37282164  0.54243144  0.75284272]
 [ 0.49933945  0.80112513 -0.32993732]
 [-0.7820896   0.2529163  -0.5695342 ]]
真实平移向量 t_true： [-0.62547983 -0.29262193  0.72328929]


In [20]:
t_x = np.array([
    [0, -t_true[2], t_true[1]],
    [t_true[2], 0, -t_true[0]],
    [-t_true[1], t_true[0], 0]
])
E = t_x @ R_true
print("\n本质矩阵 E：\n", E)


本质矩阵 E：
 [[-0.1323103  -0.65345408  0.40529833]
 [-0.75883916  0.55052889  0.18829092]
 [-0.42142254 -0.34236027  0.42666743]]


In [21]:
U, S, Vt = np.linalg.svd(E)
W = np.array([[0, -1, 0],
              [1,  0, 0],
              [0,  0, 1]])

R1 = U @ W @ Vt
R2 = U @ W.T @ Vt
t_est = U[:, 2]

if np.linalg.det(R1) < 0:
    R1 = -R1
if np.linalg.det(R2) < 0:
    R2 = -R2
print("\n候选解：")
print("R1 =\n", R1)
print("R2 =\n", R2)
print("t_est = ", t_est)


候选解：
R1 =
 [[-0.37282164  0.54243144  0.75284272]
 [ 0.49933945  0.80112513 -0.32993732]
 [-0.7820896   0.2529163  -0.5695342 ]]
R2 =
 [[ 0.97153379 -0.05358761  0.23076061]
 [-0.21924039 -0.57242642  0.7901023 ]
 [ 0.08975378 -0.81820313 -0.56788018]]
t_est =  [-0.62547983 -0.29262193  0.72328929]


In [22]:
# 4. 验证：比较 t_est 与 t_true 的方向（取绝对值避免符号差）
cos_angle = np.dot(t_est, t_true) / (np.linalg.norm(t_est) * np.linalg.norm(t_true))
print("\n平移方向余弦相似度:", abs(cos_angle))


平移方向余弦相似度: 1.0000000000000002
